### ISSUE TITLE
Domain not set

### ISSUE THREAD

**Issue by oyren** [dprandzioch/docker-ddns#28]
Hey,  probably I only configured or understood something wrong, but unfortunately I can't get any further, so I hope someone can help me.

If I run the following command (example.com is a place holder):
`
curl http://ns.example.com:8044/update?secret=testpw&domain=foo&addr=1.2.3.4
`
I get:
`{"Success":false,"Message":"Domain not set","Domain":"","Domains":[""],"Address":"","AddrType":""}`

I also tried to setup a reserve proxy with SSL (haproxy), but i just get 503 Error.
` https://ns.example.com/update?secret=testpw&domain=foo&addr=1.2.3.4`
503 Service Unavailable

Here is what I configured:
![ddns_1](https://user-images.githubusercontent.com/15930073/53243463-339f6300-36a8-11e9-8a85-3d2985bec4eb.png)
![ddns_2](https://user-images.githubusercontent.com/15930073/53243462-339f6300-36a8-11e9-9c21-35c56f189e53.png)

haproxy.cfg
```
backend dyndns_backend
    http-request set-header X-Forwarded-Port %[dst_port]
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    #http-request set-header Host www.example.com
    hash-type consistent
    option forwardfor
    cookie SERVERID insert indirect nocache

    #<name> <adress>
    server is_dyndns ddns:8044 
```

docker-compose.yml
```
        ddns:
                image: davd/docker-ddns:latest
                ports:
                        - "53:53"
                        - "53:53/udp"
                        - "8044:8080"
                networks:
                        - gateway
                environment:
                        RECORD_TTL: 60
                        ZONE: dyndns.example.com
                        SHARED_SECRET: testpw
                restart: unless-stopped
```
