### ISSUE TITLE
help with docker stack and dns record setup

### ISSUE THREAD

**Issue by m0t0k0-2501** [dprandzioch/docker-ddns#57]
Hello, I'm pretty new with docker and I'm trying to create a stack, this is what i have in my .yml

```
version: '3.8'

services:

        ddns:
                image: davd/docker-ddns:latest
                environment:
                        - "RECORD_TTL: 60"
                        - "ZONE: domain.com"
                        - "SHARED_SECRET: secret"
                ports:
                        - "80:8080"
                        - "53:53"
                        - "53:53/udp"
```
the service error is telling me that the SHARED_SECRET isn't set, this is the error message:
| SHARED_SECRET not set
| Starting domain name service...: bind9.
| panic: open /etc/dyndns.json: no such file or directory

(I'm guessing its looking for that directory in the container?)

anyway, other than this, I was reading some other  issues on this github and I'm guessing im supposed to create an A record called ns.domain.com and also a NS record that points to this container at ddns.domain.com?

I'm using namecheap so would this be right?
![image](https://user-images.githubusercontent.com/66583242/90838730-99af8980-e323-11ea-8484-f78c15ec3a56.png)

If so I'm a little confused as to how namecheap would know what ddns.domain.com is, would i also have to create an A record saying that ddns.domain.com is the same host as ns.domain.com???
